### ISSUE TITLE
Build fails on Android

### ISSUE THREAD

**Issue by surdu** [hypery2k/nativescript-fabric#118] opened 2018-01-11 16:14 UTC
**Steps to reproduce:**

1. `tns create TestApp` (make sure you have the latest nativescript)
2. add the `fabric.json` file
3. Add the API-Key to the `AndroidManifest.xml`
4. `tns run android`

**Expected:**
The build should work

**Actual:**
When trying to build the Android app, the build fails with the following error:

```
* What went wrong:
A problem occurred evaluating project ':fabric'.
> Failed to apply plugin [id 'io.fabric']
   > Crashlytics was applied to a project without an Android plugin. Please make sure the 
     Crashlytics plugin is applied after the appropriate Android plugin for your project.
```

The full output [can be found here](https://gist.github.com/surdu/ec4abf542123359da31b631425ef7a15).

**Versions:**
```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date  │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

$ node --version
v7.7.2

$ npm --version
4.6.1
```

**Java version:** 8 build 131

**Comment by hypery2k** [comment] 2018-01-11 16:38
which version of the plugin you're using?

I already tried to solve these issues, but didn't find a right, see [here](https://github.com/NativeScript/android-runtime/issues/358)

Don't have any further idea what's wrong and also not that much time for more investigation

**Comment by surdu** [comment] 2018-01-11 16:41
I'm using the `@next` version

**Comment by surdu** [comment] 2018-01-11 16:41
I'm using the `@next` version

**Comment by surdu** [comment] 2018-01-11 20:00
@hypery2k Looking at the issue you mentioned, looks like those are runtime issues, whereas this one is a build issue.

**Comment by hypery2k** [comment] 2018-01-11 20:05
you're right, but to be honest, I tried to fix the runtime issue and now creating this one you wanted.
As for now I'm giving up. I've got no idea what's this gradle foo all about...

Please don't use the @nextversion it's only a dev preview

**Comment by surdu** [comment] 2018-01-11 20:09
Using `nativescript-fabric@1.0.6` and I have the same issue 😞

**Comment by hypery2k** [comment] 2018-01-11 20:20
as already mentioned I don't exactly know why it's not working anymore.

**Comment by surdu** [comment] 2018-01-11 20:44
I managed to make the build work by manually patching the `platforms/android/app/build.gradle` with the contents of `platforms/android/build-tools/fabric-devtools/build.gradle` as [described here](https://fabric.io/kits/android/crashlytics/install). 

But now I have a runtime error ... 😞 :

```
Process com.my.app (pid 4339) has died: vis  +99TOP
```

I'm not familiar with gradle, but this hints me that maybe some gradle execution order was changed in the new NS ... ?

But even if this is fixed, then it's the runtime error ...

**Comment by hypery2k** [comment] 2018-01-15 03:15
duplicate of #114

**Closed** 2018-01-15 03:15 UTC
Labels: bug, platform:android
