### ISSUE TITLE
After 1.0.6 update, plugin crashes the app

### ISSUE THREAD

**Issue by Ablankzin** [hypery2k/nativescript-fabric#90] opened 2017-07-28 20:23 UTC
Hello,

i'm using NS 3.1.2, Node 6.11.1, on android using angular.

And after i put all requisites of README, the app keeps crashing after startup. It doesn't load main.ts and crashes. 

There is no output errors.

**Comment by alexdohmen** [comment] 2017-07-29 07:37
NS 3.1.3, node 8.1.2

APK is missing fabric classes:

$ adb logcat
07-29 09:27:00.590 28534 28534 D AndroidRuntime: Shutting down VM
07-29 09:27:00.596 28534 28534 W System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.****/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
07-29 09:27:00.596 28534 28534 W System.err: Calling js method onActivityStarted failed
07-29 09:27:00.596 28534 28534 W System.err:
07-29 09:27:00.596 28534 28534 W System.err: Error: java.lang.ClassNotFoundException: io.fabric.sdk.android.Fabric$Builder
07-29 09:27:00.596 28534 28534 W System.err:     java.lang.Class.classForName(Native Method)
07-29 09:27:00.596 28534 28534 W System.err:     java.lang.Class.forName(Class.java:400)
07-29 09:27:00.596 28534 28534 W System.err:     java.lang.Class.forName(Class.java:326)

**Comment by alexdohmen** [comment] 2017-07-29 07:54
works if u re-run it

**Comment by Ablankzin** [comment] 2017-08-01 15:21
The problem persists. I cleaned my project and the problem continues.

**Comment by Ablankzin** [comment] 2017-08-01 15:42
My logcat:

https://gist.github.com/Ablankzin/1acbf88b6473a57be9df63737b756c64

**Comment by alexdohmen** [comment] 2017-08-02 07:45
@Ablankzin 
>> Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found
try to install nativescript-dev-android-snapshot
I had the same issue

**Comment by Ablankzin** [comment] 2017-08-02 13:54
The android-snapshot are deprecated, is now integrated with Webapck bundling. I'm using webpack in my project, but the problem is when i build without webpack. I will try test with webpack android bundle.

**Comment by Ablankzin** [comment] 2017-08-02 14:05
Same issue with webpack. :(

**Comment by odnamrataizem** [comment] 2017-08-04 19:06
Webpack (actually, `nativescript-dev-webpack`) ended up working for me, as per what @Ablankzin said.

That said, while I reckon I'm still new at developing with NativeScript, *debugging* my app becomes painful if it's built with Webpack. I'd use Webpack, therefore, for *production* only, and as I said, it's working fine. What exactly makes (or: why does) `nativescript-fabric` require `libsnapshot.so`?

**Comment by hypery2k** [comment] 2017-08-07 08:23
I will try to enhance my end2end test without using libsnapshot. The plugin itself is not requiring the android-snapshot

**Comment by hypery2k** [comment] 2017-11-16 04:18
could you try with `nativescript-fabric@1.0.6-ci-build-19`?

**Comment by hypery2k** [comment] 2018-01-15 03:15
duplicate of #114

**Closed by hypery2k** 2018-01-15 03:15 UTC
Labels: bug, platform:android
