### ISSUE TITLE
App crashes on startup with Android

### ISSUE THREAD

**Issue by etabakov** [hypery2k/nativescript-fabric#114] opened 2017-11-08 14:42 UTC
## What did you do?

Installed the nativescript-fabric plugin and ran `tns run android`. 

## What did you expect to happen?

The application to start as normal. No issues are observed when running on iOS. 

## What happened instead?

The application crashes. The log file can be seen in [this Gist](https://gist.github.com/etabakov/110ad7cd2ae17f26d97c62092150d8aa).

## Your Environment

**NativeScript version:** 3.3. Tried with 3.2 and the results is the same.
**Java version:** `java version "1.8.0_144"`
**NodeJS and NPM version:** npm 5.4.2, node 6.10.0
**Platform(s) running:** Android

## Demo Project

You can checkout this branch: https://github.com/etabakov/fivekmrun-app/tree/fabric-android-crash Just clone and run on Android. No further action is needed.

I'm willing to help with the investigation and contribute in any way. Just don't know how to tackle this.

**Comment by hypery2k** [comment] 2017-11-16 04:11
could you try with `nativescript-fabric@1.0.6-ci-build-19`?

**Comment by etabakov** [comment] 2017-11-16 13:20
Just tried and the result is the same.

**Comment by hypery2k** [comment] 2017-11-16 20:48
did you removed `node_modules`and `platforms`before updating the plugin?

**Comment by etabakov** [comment] 2017-11-18 16:07
Just double checked with claned `node_modules` and `platforms`.

**Comment by surdu** [comment] 2018-01-30 09:13
Is the fix for this public yet ?

**Comment by hypery2k** [comment] 2018-01-31 20:13
Give `nativescript-fabric@1.0.6-bugfix-114-app-15` a try

**Comment by etabakov** [comment] 2018-02-01 10:01
Just tried it again. The error log can be found in [this gist](https://gist.github.com/anonymous/bfa1dfa1a0ff54d605db5c74f1337162). 

I've updated [my branch](https://github.com/etabakov/fivekmrun-app/tree/fabric-android-crash), so you can test with it as well.

Is there anything additional that I should make to make it work?

**Comment by surdu** [comment] 2018-02-22 08:56
Does this continue to be caused by [the android-runtime issue](https://github.com/NativeScript/android-runtime/issues/358) or is it something else ?

**Comment by hypery2k** [comment] 2018-02-22 11:25
currently not sure. Did had time to dive deeper into this.

**Comment by Tronix117** [comment] 2018-02-28 17:32
This issue is kind of blocking, any workaround, even temporary ?

**Comment by hypery2k** [comment] 2018-02-28 17:37
no currently not, not really a guess why and don’t think that i will solve it soon

**Comment by daveware-nv** [comment] 2018-03-14 21:00
I have a workaround that I've been using
caveats:
- I don't know why this "works"
- I've done some other tinkering (ugly hacks) to in some of my projects to get the plugin to work on  nativescript 3.4. But from memory this also worked on nativescript 3.0-3.3

Steps:
- build the app (this will crash on startup)
- delete the build folder in platforms (``platforms/android/build`` for nativescript < 3.4, if you've managed to bypass the other issues on >=3.4 then ``platforms/android/app/build``)
- build the app again (this one doesn't crash on startup for some reason)

**Comment by surdu** [comment] 2018-03-15 10:00
Hmm... This reminds me of some [small problem I saw in the code](https://github.com/hypery2k/nativescript-fabric/blob/develop/src/lib/postinstall.js#L3186):

The correct path in the new versions of NS is: `platforms/android/app/src/main/res`. Note the `/app` part in the path here, which seems to be missing from the code.

Could this be the problem ? (I don't have now the time to test 😞)

**Comment by hypery2k** [comment] 2018-03-17 09:10
@surdu thanks for the suggestion, but on a bugfix branch this is already [applied](https://github.com/hypery2k/nativescript-fabric/blob/bugfix/114_app_crash/publish/scripts/postinstall.js#L461) and it still crashes.

Have no idea why and also no time to time further into this. 

Currently thinking of deprecating the complete plugin

**Comment by EddyVerbruggen** [comment] 2018-05-01 10:29
This can probably be closed now.

**Comment by hypery2k** [comment] 2018-05-01 11:53
thanks for coming back to this, but unfortunately it still not working. I've applied your changes on older code branch, the build went through, but UI tests are still not working, see [here](https://travis-ci.org/hypery2k/nativescript-fabric/builds/372702137).
If you have a clue why it's not working any PR would be welcome.

**Comment by EddyVerbruggen** [comment] 2018-05-01 12:02
If you look at the error details (also for iOS!) then you'll see it's related to appium.

<img width="939" alt="screen shot 2018-05-01 at 14 01 26" src="https://user-images.githubusercontent.com/1426370/39472207-27e5f7c6-4d48-11e8-958a-a49297499417.png">

**Comment by hypery2k** [comment] 2018-05-01 14:10
seems to [still not to work](https://travis-ci.org/hypery2k/nativescript-fabric/builds/373461987) :(

**Comment by EddyVerbruggen** [comment] 2018-05-01 14:13
@hypery2k Be as it may, that has nothing to do with this change, right? "The environment you requested was unavailable."

**Comment by hypery2k** [comment] 2018-05-01 14:18
no the environment is created. If i look at the saucelabs console, i can see it. I’m using the same appium capabilities as the facebook plugin and there it’s working

**Comment by EddyVerbruggen** [comment] 2018-05-01 14:30
I'm just trying to make the point that that error has nothing to do with this issue so this one can be closed.

One difference between this plugin and nativescript-facebook is that its appium config grabs the built apk [from a different folder](https://github.com/NativeScript/nativescript-facebook/blob/82094b6a2d787dca9f9308a4a18f069271a612a8/.travis.yml#L7).

**Comment by hypery2k** [comment] 2018-05-01 20:01
you're right about that

**Closed by hypery2k** 2018-05-01 20:01 UTC
Labels: bug, platform:android

**Comment by hypery2k** [comment] 2018-05-02 11:44
a new preview for the package can be tested:
`
nativescript-fabric@2.0.0-develop-129
`

**Comment by etabakov** [comment] 2018-05-02 15:41
I tried the new package but I got the following error on build (also reproducible on a new plain project):

```
Gradle build...
         + applying user-defined configuration from /Users/etabakov/work/GitHub/etabakov/test-fabric/app/App_Resources/Android/app.gradle
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/etabakov/work/GitHub/etabakov/test-fabric/node_modules/nativescript-fabric/platforms/android/include.gradle' line: 26

* What went wrong:
A problem occurred evaluating script.
> Plugin with id 'io.fabric' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

**Comment by EddyVerbruggen** [comment] 2018-05-02 18:06
@etabakov I have no trouble running `nativescript-fabric@2.0.0-develop-129`. you issue smells like  `hooks/after_prepare/nativescript-fabric-gradle.js` is missing. Did you perhaps do `npm i` instead of `tns plugin add`?

Anyway, my steps were (NativeScript CLI 4.0.0):

```
tns create fabrictest --template tns-template-blank-ts
cd fabrictest
npm i
tns plugin add nativescript-fabric@2.0.0-develop-129   
```

Edit `app/App_Resources/AndroidManifest.xml` and add the API key as mentioned in the readme.

```
tns run android
```

**Comment by hypery2k** [comment] 2018-05-03 02:43
I can reproduce the error, see #125
