### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by surdu** [hypery2k/nativescript-fabric#110] opened 2017-10-10 12:28 UTC
This one is very weird, as it worked perfectly until now.

On android, the app builds ok, but when I try to run it it crashes immediately with the following error (extracted from logcat, because {N} it just informs me the process has died):

```
10-10 11:46:34.625 23482 23482 F libc    : /usr/local/google/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type tns::NativeScriptException" failed
10-10 11:46:34.625 23482 23482 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 23482 (ript.nsworktrak)
```

[Here you and find the full error](https://pastebin.com/8pBDFx0f).

On iOS, the app just remain frozen on the splash screen.

We only need to add fabric as dependency and it breaks the app (we don't need to call init). As soon as I remove nativescript-fabric plugin, everything works again.

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.1           │ 3.2.1          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

$ npm -v
4.6.1

$ node -v
v7.7.2
```

**Comment by surdu** [comment] 2017-10-11 09:23
[This issue in {N}](https://github.com/NativeScript/android-runtime/issues/785)  may help fixing this one, but unfortunetly I'm not experienced enough with android to understand the inner workings at that level.

**Comment by hypery2k** [comment] 2017-11-16 04:12
could you try with `nativescript-fabric@1.0.6-ci-build-19`?

**Comment by hypery2k** [comment] 2018-01-15 03:13
duplicate of #114

**Closed by hypery2k** 2018-01-15 03:13 UTC
Labels: bug, platform:android

**Comment by surdu** [comment] 2018-01-15 08:50
Well, technically, #114 is a duplicate of this :P

**Comment by hypery2k** [comment] 2018-01-15 09:07
You’re right, but there’s a linked sample 😉
